### ISSUE TITLE
Compilation failure : wrong version class file

### ISSUE THREAD

**Issue by Laso83** [ec-jrc/cise-sim#1]
Hello,

I try to compile cise-sim project on windows with a bash (and also with git bash) .

I have the following compilation failure : 

```
eclipse-workspace/cise-sim/cise-sim-domain/src/main/java/eu/cise/sim/engine/DispatchResult.java:[35,39] cannot access eu.cise.servicemodel.v1.message.Acknowledgement
[ERROR]   bad class file: .m2\repository\eu\europa\ec\jrc\marex\eucise-service-model\1.0.9-jdk11-SNAPSHOT\eucise-service-model-1.0.9-jdk11-SNAPSHOT.jar(eu/cise/servicemodel/v1/message/Acknowledgement.class)
[ERROR]     class file has wrong version 55.0, should be 52.0
[ERROR]     Please remove or make sure it appears in the correct subdirectory of the classpath.
```
I tryed to remove the eucise-service-model-1.0.9-jdk11-SNAPSHOT.jar,
I try to put my build path in jre-1.8

I searched if other solutions exist, but I did't find anything

I have no more ideas to correct this problem... 

I use Java 8.

Thank you in advance for your answer.

**Comment by antonis-myst** [comment]
Hi,

The corresponding libraries as you can see have been built with jdk11. Is it possible for you to switch to jdk11 and retry?

Thanks,
Antonis

**Comment by Laso83** [comment]
Ok thanks, that's worked !
