### ISSUE TITLE
Request for cise-signature-2.2.1.jar source code

### ISSUE THREAD

**Issue by YannGarcia** [ec-jrc/cise-sim#6]
Good morning,

I'm Yann Garcia from FSCOM and I'm involved in the ETSI STF 637 project on CISE data model - 101099627. I'm working on the conformance testing.

To help me in the during the process of validating (and sometime debugging) of CISE node implementations, I would like to have a access to the source code of the cise-signature-2.2.1 library in order to add logs or to introduce some XMLDSIG protocol violation for invalid behavior tests.

I can sign a NDA if required either in the context of the ETSI STF 637 project or directly with my company.

Many thanks in advance for your understanding,

Best regards,

Yann Garcia
Senior Software Engineer
Microsoft MCAD.net Certified
**************************************
FSCOM SARL
Le Montespan B2
6, Avenue des Alpes
F-06600 Antibes, FRANCE
************************************************
Tel: +33 (0)4 92 94 49 08 (GMT+1)
Mobile: +33 (0)6 68 94 57 76 (GMT+1)
Email: [yann.garcia@fscom.fr](mailto:yann.garcia@fscom.fr)
Skype: yann.garcia
SlackID: U0263576GG3, U02T8HUD2KX

**Comment by antonis-myst** [comment]
Hi Yann,

Requests to access to the source code of CISE libraries should be addressed to Maritime Support Service (mss@emsa.europe.eu).

Thanks for your inquiry,
Antonis Mystakidis
